apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-api.fullname" . }}
  namespace: default
  labels:
    jke/workload: {{ include "users-api.fullname" . }}

spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "users-api.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "users-api.fullname" . }}
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: {{ .Values.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.db.port | quote }}
        - name: DB_NAME
          value: {{ .Values.db.dbName }}
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: api-creds
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: api-creds
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: db-auth
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-auth
      {{- if eq .Values.global.env "dev" }}
        image: "users_api:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: users-api
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-users-api
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
