image:
  name: thehubpub
  repository: jalgraves/hubpub
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 3037

ingress:
  enabled: false

ingressHost: ""
