apiVersion: v1
kind: Service
metadata:
  name: wavelengths
  namespace: default
spec:
  ports:
  - name: tcp-wavelengths
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
  - name: http
    port: 80
    targetPort: {{ .Values.containerPort }}
  selector:
    app: wavelengths
