apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beantown.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - env:
        - name: API_USER_PW
          valueFrom:
            secretKeyRef:
              key: password
              name: api-user
        image: {{ include "imageString" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "beantown.fullname" . }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-beantown
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {}
