apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beantown.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "beantown.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "beantown.fullname" . }}
    spec:
      containers:
      - env:
        - name: CONTACT_API_HOST
          value: {{ .Values.contactApiHost }}
        - name: CONTACT_API_PROTOCOL
          value: {{ .Values.contactApiProtocol }}
        - name: MENU_API_HOST
          value: {{ .Values.menuApiHost }}
        - name: MENU_API_PROTOCOL
          value: {{ .Values.menuApiProtocol }}
        - name: MERCH_API_HOST
          value: {{ .Values.merchApiHost }}
        - name: MERCH_API_PROTOCOL
          value: {{ .Values.merchApiProtocol }}
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: api-creds
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: api-creds
      {{- if eq .Values.global.env "dev" }}
        image: "beantown:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: {{ include "beantown.fullname" . }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-beantown
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {}
