apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jal-postgres.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-db
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pg-db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-auth
              key: password
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: pg-db
        ports:
        - containerPort: 5432
          name: tcp-pg-db
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false