apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
    role: primary
  name: data-postgres-postgresql-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
  volumeName: pvc-d826463a-76cb-4b2d-97e2-e7030787395b
