apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: default
spec:
  ports:
  - name: tcp-postgres
    nodePort: 32432
    port: 5432
  selector:
    app: pg-db
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  ports:
  - name: tcp-postgres
    port: 5432
    targetPort: tcp-pg-db
  selector:
    app: pg-db