{{- if eq .Values.global.env "prod" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "drdavisicecream.fullname" . }}
spec:
  hosts:
  - "{{ include "drdavisicecream.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ include "drdavisicecream.fullname" . }}.{{ .Release.Namespace }}.drdavisicecream.com"
  - "drdavisicecream.com"
  - "www.drdavisicecream.com"
  gateways:
  - istio-ingress/web-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.containerPort }}
        host: "{{ include "drdavisicecream.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: {{ include "drdavisicecream.fullname" . }}
{{- end }}
