apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin.fullname" . }}
spec:
  ports:
  - name: "tcp-{{ include "admin.fullname" . }}"
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "admin.fullname" . }}
