apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contact-api.fullname" . }}
  labels:
    jke/workload: {{ include "contact-api.fullname" . }}
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      jke/workload: {{ include "contact-api.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "contact-api.fullname" . }}
        jke/workload: {{ include "contact-api.fullname" . }}
    spec:
      containers:
      - env:
        - name: EMAIL_RECIPIENT
          valueFrom:
            secretKeyRef:
              key: email_recipient
              name: contact-api-creds
              optional: false
        - name: SECOND_EMAIL_RECIPIENT
          valueFrom:
            secretKeyRef:
              key: second_email_recipient
              name: contact-api-creds
              optional: false
        - name: SLACK_WEBHOOK_USER
          valueFrom:
            secretKeyRef:
              key: slack_user
              name: contact-api-creds
        - name: SLACK_WEBHOOK_CHANNEL
          valueFrom:
            secretKeyRef:
              key: slack_channel
              name: contact-api-creds
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: slack_webhook_url
              name: contact-api-creds
              optional: false
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              key: api_user
              name: app-creds
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: api_pass
              name: app-creds
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: contact-api-creds
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: contact-api-creds
              optional: false
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              key: aws_default_region
              name: contact-api-creds
              optional: false
      {{- if eq .Values.global.env "dev" }}
        image: "contact_api:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: contact-api
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-contact-api
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
