{{- if eq .Values.global.env "prod" }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "contact-api.fullname" . }}
spec:
  host: "{{ include "contact-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
  - name: {{ include "contact-api.fullname" . }}
{{- end }}
