apiVersion: v1
data:
  pg_user.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE USER jalbot;
        CREATE DATABASE jalbot;
        GRANT ALL PRIVILEGES ON DATABASE jalbot TO jalbot;
        CREATE DATABASE food OWNER jalbot;
        CREATE DATABASE messages OWNER jalbot;
        CREATE DATABASE users OWNER jalbot;
        CREATE DATABASE merch OWNER jalbot;
        CREATE DATABASE orders OWNER jalbot;
        CREATE DATABASE sessions OWNER jalbot;
    EOSQL
kind: ConfigMap
metadata:
  name: db-bootstrap
  namespace: default
